language: node_js
sudo: false
node_js:
  - "node"
  - "6"

addons:
  apt:
    packages:
    - beanstalkd

env:
- TEST_CMD=test
- TEST_CMD="run integration-test"

before_install:
- echo 'starting queue'
- bin/start-queue.sh &
- jobs -l

after_script:
- npm install -g npm-check
- npm-check

script:
- npm $TEST_CMD

